# Bash prompt
PS1='\W  \$ '

if [ -f ~/.git-prompt.sh ]; then
    . ~/.git-prompt.sh
fi

export GIT_PS1_SHOWDIRTYSTATE=1
export PS1='\w$(__git_ps1 " (%s)") \$ '

if [ -f ~/.git-completion.bash ]; then
      . ~/.git-completion.bash
fi

# Aliases
alias ll='ls -hl'
alias lr='ls -hlR'
alias ..='cd ..'
alias cls='clear'
alias size='du -sh'
alias less='less -N'
